//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rinaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DK_R : DbContext
    {
        public DK_R()
            : base("name=DK_R")
        {
        }
        public static DK_R dK_R;
        public static DK_R GetContext()
        {
            if(dK_R == null)
            {
                dK_R = new DK_R();
            }
            return dK_R;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<ContactPerson> ContactPerson { get; set; }
        public virtual DbSet<gruppa> gruppa { get; set; }
        public virtual DbSet<Krujok> Krujok { get; set; }
        public virtual DbSet<krujok_child> krujok_child { get; set; }
        public virtual DbSet<Prepods> Prepods { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
    }

}
