//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rinaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class krujok_child
    {
        public int id_child { get; set; }
        public int id_krujok { get; set; }
        public System.DateTime data_start { get; set; }
        public Nullable<System.DateTime> data_finish { get; set; }
        public int id { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Krujok Krujok { get; set; }
    }
}
