//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rinaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepods
    {
        public int id { get; set; }
        public string seria_pasport { get; set; }
        public string nomer_pasport { get; set; }
        public string FIO { get; set; }
        public int age { get; set; }
        public string pol { get; set; }
        public string semeinoe_polojenie { get; set; }
        public string obrazovanie { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
        public int id_specialization { get; set; }
    }
}
